//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristica_Tipo_Habitacion
    {
        public int id_Caracteristica_Tipo_Habitacion { get; set; }
        public int idCaracteristica_Caracteristica_Tipo_Habitacion { get; set; }
        public string tipo_Habitacion_Caracteristica_Tipo_Habitacion { get; set; }
    
        public virtual Caracteristica Caracteristica { get; set; }
        public virtual Tipo_Habitacion Tipo_Habitacion { get; set; }
    }
}
