//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad_SubEntidad_Imagen
    {
        public int id_Entidad_SubEntidad_Imagen { get; set; }
        public int idEntidad_Entidad_SubEntidad_Imagen { get; set; }
        public int idSubEntidad_Entidad_SubEntidad_Imagen { get; set; }
        public int idImagen_Entidad_SubEntidad_Imagen { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual Imagen Imagen { get; set; }
        public virtual SubEntidad SubEntidad { get; set; }
    }
}
