//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facilidad
    {
        public string id_Facilidad { get; set; }
        public string descripcion_Facilidad { get; set; }
        public string hotel_Facilidad { get; set; }
        public string nombre_Facilidad { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
