//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facilidad
    {
        public string id_Facilidad { get; set; }
        public string descripcion_Facilidad { get; set; }
        public string hotel_Facilidad { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
