//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitacion()
        {
            this.Caracteristica_Habitacion = new HashSet<Caracteristica_Habitacion>();
            this.Reservacion = new HashSet<Reservacion>();
        }
    
        public int numero_Habitacion { get; set; }
        public string tipo_Habitacion { get; set; }
        public string descripcion_Habitacion { get; set; }
        public string estado_Habitacion { get; set; }
        public double tarifa { get; set; }
        public System.Guid fileIDimagen_Habitacion { get; set; }
        public byte[] imagen_Habitacion { get; set; }
        public string hotel_Habitacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caracteristica_Habitacion> Caracteristica_Habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservacion> Reservacion { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
