//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Facilidad = new HashSet<Facilidad>();
            this.HotelAdministrador = new HashSet<HotelAdministrador>();
            this.Tipo_Habitacion = new HashSet<Tipo_Habitacion>();
            this.HotelPublicidad = new HashSet<HotelPublicidad>();
        }
    
        public string nombre_Hotel { get; set; }
        public string descripcion_Hotel { get; set; }
        public string sobreNosotros_Hotel { get; set; }
        public string latitud_Hotel { get; set; }
        public string longitud_Hotel { get; set; }
        public string comoLlegar_Hotel { get; set; }
        public string telefono_Hotel { get; set; }
        public Nullable<int> aptoPostal_Hotel { get; set; }
        public string email_Hotel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facilidad> Facilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelAdministrador> HotelAdministrador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Habitacion> Tipo_Habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelPublicidad> HotelPublicidad { get; set; }
    }
}
