//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPublicidad
    {
        public int id_HotelPublicidad { get; set; }
        public int idPublicidad_HotelPublicidad { get; set; }
        public string Hotel_HotelPublicidad { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Publicidad Publicidad { get; set; }
    }
}
