//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelAdministrador
    {
        public int id_HotelAdministradores { get; set; }
        public int idAdministrador_HotelAdministradores { get; set; }
        public string Hotel_HotelAdministradores { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
