//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesPiscina
    {
        public string descripcion_Entidad { get; set; }
        public string descripcion_SubEntidad { get; set; }
        public string descripcion_Imagen { get; set; }
        public byte[] imagen_Imagen { get; set; }
    }
}
