//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesHotel
    {
        public string descripcion_Entidad { get; set; }
        public string descripcion_SubEntidad { get; set; }
        public string descripcion_Imagen { get; set; }
        public byte[] imagen_Imagen { get; set; }
    }
}
