//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion
    {
        public int id_Promocion { get; set; }
        public System.DateTime inicio_Promocion { get; set; }
        public System.DateTime fin_Promocion { get; set; }
        public int descuento_Promocion { get; set; }
        public int estado_Promocion { get; set; }
        public string tipo_Habitacion_Promocion { get; set; }
    
        public virtual Tipo_Habitacion Tipo_Habitacion { get; set; }
    }
}
