//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion
    {
        public int id_Promocion { get; set; }
        public System.DateTime inicio_Promocion { get; set; }
        public System.DateTime fin_Promocion { get; set; }
        public int descuento_Promocion { get; set; }
        public int estado_Promocion { get; set; }
        public string tipo_Habitacion_Promocion { get; set; }
    
        public virtual Tipo_Habitacion Tipo_Habitacion { get; set; }
    }
}
