//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int id_Reservacion { get; set; }
        public System.DateTime fechaLLegada_Reservacion { get; set; }
        public System.DateTime fechaSalida_Reservacion { get; set; }
        public int idHabitacion_Reservacion { get; set; }
        public string idCliente_Reservacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
