//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCore.dominio.entidades.Objetos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int id_Reservacion { get; set; }
        public System.DateTime fechaLLegada_Reservacion { get; set; }
        public System.DateTime fechaSalida_Reservacion { get; set; }
        public int idHabitacion_Reservacion { get; set; }
        public string idCliente_Reservacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
